AllCops:
  Include:
    - '**/*.rake'
    - '**/Gemfile'
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'spec/spec_helper.rb'

AccessorMethodName:
  Enabled: false

Alias:
  Enabled: false

ArrayJoin:
  Enabled: false

AsciiComments:
  Enabled: false

AsciiIdentifiers:
  Enabled: false

Attr:
  Enabled: true

BlockNesting:
  Enabled: true

CaseEquality:
  Enabled: true

CharacterLiteral:
  Enabled: true

ClassLength:
  Enabled: false

ClassVars:
  Enabled: false

CollectionMethods:
  PreferredMethods:
    find: detect
    reduce: inject
    collect: map
    find_all: select

ColonMethodCall:
  Enabled: false

CommentAnnotation:
  Enabled: false

CyclomaticComplexity:
  Enabled: false

Delegate:
  Enabled: true

DeprecatedHashMethods:
  Enabled: false

Documentation:
  Enabled: false

DotPosition:
  EnforcedStyle: trailing

DoubleNegation:
  Enabled: true

EmptyLiteral:
  Enabled: true

Encoding:
  Enabled: false

EvenOdd:
  Enabled: false

FileName:
  Enabled: false

FlipFlop:
  Enabled: false

FormatString:
  Enabled: false

GlobalVars:
  Enabled: false

IfUnlessModifier:
  Enabled: false

IfWithSemicolon:
  Enabled: false

Lambda:
  Enabled: false

LambdaCall:
  Enabled: false

LineEndConcatenation:
  Enabled: false

LineLength:
  Max: 95

MethodLength:
  Enabled: false

ModuleFunction:
  Enabled: false

NegatedIf:
  Enabled: false

NegatedWhile:
  Enabled: false

NilComparison:
  Enabled: true

Not:
  Enabled: false

NumericLiterals:
  Enabled: true

OneLineConditional:
  Enabled: false

OpMethod:
  Enabled: false

ParameterLists:
  Enabled: false

PercentLiteralDelimiters:
  PreferredDelimiters:
    '%': '{}'

PerlBackrefs:
  Enabled: false

PredicateName:
  NamePrefixBlacklist:
    - is_

Proc:
  Enabled: false

RaiseArgs:
  Enabled: false

RegexpLiteral:
  Enabled: false

SelfAssignment:
  Enabled: false

SingleLineBlockParams:
  Enabled: false

SingleLineMethods:
  Enabled: false

SignalException:
  Enabled: false

SpecialGlobalVars:
  Enabled: false

StringLiterals:
  EnforcedStyle: single_quotes

VariableInterpolation:
  Enabled: false

TrailingComma:
  Enabled: true

TrivialAccessors:
  Enabled: false

VariableInterpolation:
  Enabled: false

WhenThen:
  Enabled: false

WhileUntilModifier:
  Enabled: false

WordArray:
  Enabled: false

# Lint

AmbiguousOperator:
  Enabled: true

AmbiguousRegexpLiteral:
  Enabled: false

AssignmentInCondition:
  Enabled: false

ConditionPosition:
  Enabled: false

DeprecatedClassMethods:
  Enabled: false

ElseLayout:
  Enabled: false

HandleExceptions:
  Enabled: true

InvalidCharacterLiteral:
  Enabled: false

LiteralInCondition:
  Enabled: false

LiteralInInterpolation:
  Enabled: false

Loop:
  Enabled: false

ParenthesesAsGroupedExpression:
  Enabled: false

RequireParentheses:
  Enabled: false

UnderscorePrefixedVariableName:
  Enabled: false

Void:
  Enabled: false
